name: Docker Image CI

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Docker image
      run: docker buildx build --ssh default . --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/buzzer-frontend:${{ github.ref_name }}
      env:
        SSH_AUTH_SOCK: ${{ env.SSH_AUTH_SOCK }}

    - name: Push the Docker image
      run: docker push ghcr.io/${{ github.repository_owner }}/buzzer-frontend:${{ github.ref_name }}